# Generated by Django 5.1.7 on 2025-03-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UplaodIamge',
            new_name='UplaodedImage',
        ),
    ]
